### ISSUE TITLE
Pastas estranhas

### ISSUE THREAD

**Issue by osmarbraz** [PedroMedeiros73423/GerenciadorFerramentas#5]
Para que estas pastas?
[GerenciadorFerramentais](https://github.com/PedroMedeiros73423/GerenciadorFerramentas/blob/main/GerenciadorFerramentais)
e
[GerenciadorFerramentas](https://github.com/PedroMedeiros73423/GerenciadorFerramentas/blob/main/GerenciadorFerramentas)

**Comment by Turchiellows** [comment]
Pastas removidas
